version: "3.9"
services:
  nginx:
    image: docker.io/library/nginx
    depends_on:
      - php-fpm
      - mariadb
    volumes:
      - "./app/:/app/:z"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf:z"
    working_dir: /app
    ports:
      - "8080:80"

  php-fpm:
    build: docker-images/php-fpm
    volumes:
      - "./app/:/app/:z"
      - "./config/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini:z"
      - "./config/fix-permissions.sh:/root/fix-permissions.sh:z"
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mariadb:
    image: docker.io/library/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    volumes:
      - "./config/initdb.d/:/docker-entrypoint-initdb.d/:z"
    ports:
      - "3306:3306"

  pma:
    image: docker.io/library/phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: "${MARIADB_USER}"
      PMA_PASSWORD: "${MARIADB_PASSWORD}"
      UPLOAD_LIMIT: 512M
    ports:
      - "4000:80"
