export PS1="\[\033]0;\u@\h:\W\007\]\[\033[01;32m\]\u@\h\[\033[01;36m\] \W$ \[\033[00m\]"

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

alias ..="cd .."
alias ll="ls -lah --color=auto"
